# Azure Pipeline for PaymentApp

trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'
  imageName: 'paymentapp'

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '6.0.x'

- task: JfrogCliV2@1
  inputs:
    jfrogPlatformConnection: 'soleng-maharship'
    command: 'jf rt ping'

- task: JfrogCliV2@1
  inputs:
    jfrogPlatformConnection: 'soleng-maharship'
    command: 'jf nuget restore PaymentApp/PaymentApp.csproj --url=$JFROG_URL --user=$JFROG_USER --password=$JFROG_PASSWORD --repo=$JFROG_NUGET_REPO'

- script: |
    dotnet build PaymentApp/PaymentApp.csproj --configuration $(buildConfiguration)
  displayName: 'Build project'

- script: |
    dotnet publish PaymentApp/PaymentApp.csproj --configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)
  displayName: 'Publish project'

- script: |
    ./jf rt upload $(Build.ArtifactStagingDirectory) $JFROG_ARTIFACTORY_REPO_PATH --url=$JFROG_URL --user=$JFROG_USER --password=$JFROG_PASSWORD
  displayName: 'JFrog CLI Publish Artifacts'

- script: |
    echo $JFROG_PASSWORD | docker login $JFROG_DOCKER_REGISTRY_URL -u $JFROG_USER --password-stdin
    docker build -t $JFROG_DOCKER_REGISTRY_URL/paymentapp:latest .
    docker push $JFROG_DOCKER_REGISTRY_URL/paymentapp:latest
  displayName: 'Build and Push Docker image to Artifactory'

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: 'drop'
    publishLocation: 'Container'
